[package]
authors = ["messense <messense@icloud.com>"]
build = "build.rs"
description = "BosonNLP SDK for Rust"
documentation = "https://messense.github.io/bosonnlp-rs"
homepage = "https://github.com/messense/bosonnlp-rs"
keywords = ["nlp", "bosonnlp", "tag", "ner", "sentiment"]
license = "MIT"
name = "bosonnlp"
readme = "README.md"
repository = "https://github.com/messense/bosonnlp-rs"
version = "0.3.0"

[dependencies]
error-chain = "0.5"
flate2 = "0.2"
hyper = "0.9"
log = "0.3"
serde = "0.8"
serde_json = "0.8"
url = "1.2"

[dependencies.clippy]
optional = true
version = "^0.*"

[dependencies.uuid]
features = ["v4"]
version = "0.3"

[dependencies.serde_derive]
optional = true
version = "0.8"

[features]
default = ["serde_codegen"]
unstable = ["serde_derive"]

[build-dependencies]
serde_codegen = { version = "0.8", optional = true }
