[package]
authors = ["messense <messense@icloud.com>"]
name = "bosonnlp"
version = "0.1.0"

[dependencies]
flate2 = "0.2"
hyper = "0.7"
jsonway = "0.3"
log = "0.3"
rustc-serialize = "0.3"
url = "0.5"
uuid = "0.1"
