[package]
authors = ["messense <messense@icloud.com>"]
description = "BosonNLP SDK for Rust"
keywords = ["nlp", "bosonnlp", "tag", "ner"]
license = "MIT"
name = "bosonnlp"
readme = "README.md"
version = "0.2.6"
homepage = "https://github.com/messense/bosonnlp-rs"
repository = "https://github.com/messense/bosonnlp-rs"
documentation = "https://messense.github.io/bosonnlp-rs"

[dependencies]
flate2 = "0.2"
hyper = "0.9"
jsonway = "0.3"
log = "0.3"
rustc-serialize = "0.3"
url = "1.2"
uuid = { version = "0.3", features = ["v4"] }
clippy = { version = "^0.*", optional = true }

[features]
unstable = []
